export const bingoData = [
    "\"Ta det på mail\"",
    "\"Ja, presis\"",
    "\"Today is my sentry day\"",
    "\"Du er muta\"",
    "\"Can you hear me?\"",
    "\"I'm on my way\"",
    "The breakout rooms are fucked",
    "Lars comes late to the meeting",
    "\"Dees nuts\"",
    "Eythor's pointing his camera all over the place",
    "Energy drink spotted",
    "\"How is the weather?\"",
    "\"Let's take this offline\"",
    "\"Circle back\"",
    "\"Have a nice day!\"",
    "\"See you\"",
    "Someones rubbing their eyes",
    "\"I think you're muted\"",
    "Hola or Olav? misunderstanding",
    "\"Does someone have something they wanna say?\"",
    "\"Um, I don't know whos been and not\"",
    "We can't hear Tom Stian",
    "Someones speaking polish",
    "Someones yawning",
    "A cat/dog appears on screen",
    "Someone has a pirate filter",
    "Someone comments on the time"
  ]