export const bingoData = [
    "Ta det på mail",
    "Sparre litt",
    "Flagge det",
    "Løfte i flokk",
    "Ha det i bakhodet",
    "Landet på",
    "Forankre",
    "Være på nett",
    "Ta en prat",
    "Kjøre en runde",
    "Let's take this offline",
    "Circle back",
    "Synergies",
    "Low-hanging fruit",
    "Deep dive",
    "Move the needle",
    "Bandwidth",
    "Touch base",
    "Parking lot that",
    "Align on this",
    "Unpack that",
    "Double-click on this",
    "Level-set",
    "Run it up the flagpole",
    "Boil the ocean",
    "EOD",
    "Action item",
    "Going forward",
    "Put a pin in it",
    "On my radar",
    "Loop in",
    "Ping me",
    "Hard stop",
    "Net-net",
    "Value-add",
    "Can everyone see my screen?",
    "You're on mute",
    "Sorry, you go ahead",
    "Let's timebox this",
    "In the interest of time",
    "Any questions?",
    "Great question",
    "I'll follow up on that"
  ]